name: Download New XKCD Comics

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  download-new-xkcd-comics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: |
          cd ./scraper-node
          npm install
          node index.js
      - run: |
          git config user.name jpaddeo
          git config user.email jpaddeo@gmail.com
          git add .
          git commit -m "Adding new comics"
          git push
