name: GitHub Actions Demo
on:
  workflow_dispatch:
    schedule:
      - cron: '0 0,12 * * *'
jobs:
  download-new-xkcd-comics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: cd scraper-node && npm install
      - run: cd scraper-node && node index.js
      - run: |
          git config user.name jpaddeo
          git config user.email jpaddeo@gmail.com
          git add .
          git commit -m "Add new comics"
          git push
